{
  "formatVersion": "1.1",
  "component": {
    "group": "com.frc5113",
    "module": "library",
    "version": "1.1.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "library-1.1.4.jar",
          "url": "library-1.1.4.jar",
          "size": 5187724,
          "sha512": "e92be6ec5d0dbd63346c897ee1ee892c77161f925f2b3bf03ce3d08640625768aa8226c2ccc442c945e5196e602aaaba670c0885bad651692dd6289e1fadca91",
          "sha256": "76176e213ba5e3f72ffcf0f2a24f7668f4e711bcc67701f0ff8dfa689bab04f7",
          "sha1": "f41fc63baefa1fb4389953d1ab90d209833f6581",
          "md5": "00a967f2698c93749f63d235b3f6833a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "edu.wpi.first.wpilibj",
          "module": "wpilibj-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.wpimath",
          "module": "wpimath-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.ntcore",
          "module": "ntcore-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.cscore",
          "module": "cscore-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.cameraserver",
          "module": "cameraserver-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.hal",
          "module": "hal-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.wpiutil",
          "module": "wpiutil-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "edu.wpi.first.thirdparty.frc2022.opencv",
          "module": "opencv-java",
          "version": {
            "requires": "4.5.2-1"
          }
        },
        {
          "group": "org.ejml",
          "module": "ejml-simple",
          "version": {
            "requires": "0.41"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-annotations",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-core",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.12.4"
          }
        },
        {
          "group": "edu.wpi.first.wpilibNewCommands",
          "module": "wpilibNewCommands-java",
          "version": {
            "requires": "2022.4.1"
          }
        },
        {
          "group": "com.revrobotics.frc",
          "module": "REVLib-java",
          "version": {
            "requires": "2022.1.1"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "api-java",
          "version": {
            "requires": "5.21.2"
          }
        },
        {
          "group": "com.ctre.phoenix",
          "module": "wpiapi-java",
          "version": {
            "requires": "5.21.2"
          }
        },
        {
          "group": "com.kauailabs.navx.frc",
          "module": "navx-java",
          "version": {
            "requires": "4.0.442"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "20.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "library-1.1.4.jar",
          "url": "library-1.1.4.jar",
          "size": 5187724,
          "sha512": "e92be6ec5d0dbd63346c897ee1ee892c77161f925f2b3bf03ce3d08640625768aa8226c2ccc442c945e5196e602aaaba670c0885bad651692dd6289e1fadca91",
          "sha256": "76176e213ba5e3f72ffcf0f2a24f7668f4e711bcc67701f0ff8dfa689bab04f7",
          "sha1": "f41fc63baefa1fb4389953d1ab90d209833f6581",
          "md5": "00a967f2698c93749f63d235b3f6833a"
        }
      ]
    }
  ]
}
